# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Note' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Note
pod 'AFNetworking'	,'~> 3.1.0'
pod 'Masonry'		,'~> 1.0.2'
pod 'BlocksKit'		,'~> 2.2.5'
pod 'MJExtension'	,'~> 3.0.10'
pod 'SDWebImage', 	'~> 3.7.2'
pod 'Aspects',		'~> 1.3.1'
pod 'FMDB',		'~>2.6.2'
end
